//USER STORIES
//*************** */

//PRIORITY
//1.USER SHOULD BE ABLE TO ENTER THEIR SKILL CHECKS 
//2.USER SHOULD BE ABLE TO TAB  THROUGH THEIR INPUTS
//3.CARDS FROM USER DECK SHOULD POPULATE IN DROP DOWN LIST
//4. ENTRIES SHOULD HAVE AUTO-FILL
//5. USERS CAN EDIT/DELETE THEIR LOG ENTRIES
//6. USERS CAN RECORD THEIR CAMPAIGN RESULTS/EXP/TRAUMA
//7. USERS CAN SEE SUMMARY OF MONSTER KILLS



//FUTURE        
//8. SUCESSES/FAILS SHOULD BE TOTALED AND GIVEN PERCENTAGE RESULTS

//plans to log skill checks during

//MYTHOS PHASE


//INVESTIGATION PHASE

//GENERIC LOG ENTRY
//CHARACTER-ACTION-MODIFIER(S)-TOKEN-RESULT


//*******FIGHT*******
//MARK FIGHT ROYAL EMISSARY .45/TAUNT(ICON) -2 SUCCESS
//MARK FIGHT RATS N/A  +0 SUCCESS

//*******ENGAGE*******
//MINH ENGAGE MAN-IN-PALLID-MASK

//*******INVESTIGATE*******
//MINH INVESTIGATE  MAN IN PALLID MASK MAGNIFYING-GLASS/DEDUCTION/MINH-ABILITY(1 WILD ICON)

//*******RESIGN*******
//MINH RESIGNS LOBBY 

